# List of files that can be appended in the target repos
appendable_files = [
    "CODE_OF_CONDUCT.md",
    ".github/labels.yml",
    ".gitattributes",
]

# Configlet workflow settings
configlet_configurable_keys = [
    "fmt"
]

# File-specific config
[files]
[files."CODE_OF_CONDUCT.md"]
trailing_newlines = 2

[files.".github/labels.yml"]
trailing_newlines = 2
