name: Lint whitespace

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_whitespace:
    name: Lint whitespace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Check that every file has no trailing whitespace, and exactly one final newline
        run: ./.github/bin/lint-whitespace
