name: Lint whitespace

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_whitespace:
    name: Lint whitespace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Check that every file has no trailing whitespace, and exactly one final newline
        run: ./.github/bin/lint-whitespace
