name: Lint whitespace

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_whitespace:
    name: Lint whitespace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Check that every file has no trailing whitespace, and exactly one final newline
        run: ./.github/bin/lint-whitespace
