name: Lint whitespace

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_whitespace:
    name: Lint whitespace
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - name: Check that every file has no trailing whitespace, and exactly one final newline
        run: ./.github/bin/lint-whitespace
